app <- ShinyDriver$new("../", seed = 23)
app$snapshotInit("mytest")

app$setInputs(start_date = "2004-01-02", wait_=FALSE)
app$setInputs(end_date = "2018-02-15")
app$snapshot()
app$setInputs(api = "ibuprofen")
app$setInputs(start_date = "2004-01-14")
app$setInputs(end_date = "2018-01-31")
app$setInputs(seriousness = "1")
app$snapshot()
app$setInputs(end_date = "2017-12-31")
app$setInputs(seriousness = "2")
app$snapshotDownload("download_data")
app$snapshot()
